---
title: "Week6b-Lab assignment"
author: "Helia Tehrani"
date: "2023-03-02"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github 
---

## R Markdown

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      Warning=FALSE,
                      fig.path = "../Output/")
                      
```

#Load Libraries

```{r}
library(here)
library(tidyverse)
library(palmerpenguins)
library(lubridate)
library(kableExtra)
```

## make Plots

### Read in data

```{r}
WeightData<-read_csv(here("week_2","data","weightdata.csv"))

### Data Analysis #####

head(WeightData) # Looks at the top 6 lines of the dataframe
tail(WeightData) # Looks at the bottom 6 lines of the dataframe
View(WeightData) # opens a new window to look at the entire dataframe
```

# next plot

```{r Penguinplot}
penguins %>% #using palmer dataset
  ggplot(aes(x=bill_length_mm,
             y=bill_depth_mm,
             color=species))+
  geom_point()+
  geom_smooth(method="lm")+
  labs(x="Bill Length (mm)",
       Y="Bill Depth (mm)",
       color="Species")+
  theme_dark()
```

###Tables #Tables

| Time   | Session  |   Topic |
|:-------|:--------:|--------:|
| *left* | *center* | *right* |
| 01:00  |    1     | Species |
| 01:50  |          | *Break* |
| 02:00  |    2     |  Tables |
| 02:45  |          | *Break* |

#Add some style

```{r}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>% # make it a kable table
  kable_classic()%>%
  row_spec(2, bold = T, color = "orange", background = "brown")
```
