---
title: "week_08"
author: "Helia Tehrani"
date: "2023-03-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.path = "../Output/")
```

# Libraries
```{r, Libraries}
library(tidyverse)
library(here)
library(patchwork)
library(ggrepel)
library(gganimate)
library(magick)
library(palmerpenguins)
```

# Plot 1
```{r, plot 1}
p1<-penguins %>%
  ggplot(aes(x = body_mass_g, 
             y = bill_length_mm, 
             color = species))+
  geom_point()
p1
```

# Plot 2
```{r, plot 2}
p2<-penguins %>%
  ggplot(aes(x = sex, 
             y = body_mass_g, 
             color = species))+
  geom_jitter(width = 0.2)
p2
```

# Bring the plots together
```{r, Bring the plots together}
p1+p2+ #bring plots together
  plot_layout(guides = 'collect')+ #Group the legends.
  plot_annotation(tag_levels = 'A') #Add labels (A,B)
```

# Put one plot on top of the other
```{r, Put one plot on top of the other}
p1/p2 + #Put one plot on top of the other
  plot_layout(guides = 'collect')+ ##Group the legends
  plot_annotation(tag_levels = 'A') ##Add labels (A,B)
```

# ggrepel. Use the mtcars dataset that comes with it. It is data on cars
```{r, mtcars}
ggplot(mtcars, aes(x = wt, #weight
                   y = mpg, #miles per hour
                   label = rownames(mtcars))) + #row names of cars in data
  geom_text_repel() + # creates a text label and repels them
  geom_point(color = 'red')
# Use the label function
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_label_repel() + # repel them
  geom_point(color = 'red')
```

# gganimate
```{r, gganimate}
penguins %>% #penguin data
ggplot(aes(x = body_mass_g, #body mass on x
            y = bill_depth_mm, #bill depth on y
            color = species)) + #color data by species
  geom_point()+ #puts data on a scatter lot
  transition_states( #Add a transition.
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("bounce-in-out") #Change the ease aesthetics
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("sine-in-out") +
  ggtitle('Year: {closest_state}') +
  anim_save(here("Week_8","output","mypengiungif.gif"))
```

# Magick
```{r, Magick}
penguin<-image_read("https://pngimg.com/uploads/penguin/pinguin_PNG9.png") #Put a penguin in it.
penguin
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()+
  ggsave(here("Week_8","Output","penguin.png"))
penplot<-image_read(here("Week_8","Output","penguin.png"))
out <- image_composite(penplot, penguin, offset = "+70+30")
out
```
